//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_VRBro p_VRBro;
        
        public static SteamVR_Input_ActionSet_VRBro VRBro
        {
            get
            {
                return SteamVR_Actions.p_VRBro.GetCopy<SteamVR_Input_ActionSet_VRBro>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_VRBro = ((SteamVR_Input_ActionSet_VRBro)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_VRBro>("/actions/VRBro")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.VRBro};
        }
    }
}
