//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_vRBro_InteractUI;
        
        private static SteamVR_Action_Boolean p_vRBro_SaveBuffer;
        
        private static SteamVR_Action_Boolean p_vRBro_StartBuffer;
        
        private static SteamVR_Action_Boolean p_vRBro_StopBuffer;
        
        private static SteamVR_Action_Boolean p_vRBro_StartRecording;
        
        private static SteamVR_Action_Boolean p_vRBro_StopRecording;
        
        private static SteamVR_Action_Boolean p_vRBro_StartStreaming;
        
        private static SteamVR_Action_Boolean p_vRBro_StopStreaming;
        
        private static SteamVR_Action_Boolean p_vRBro_SplitRecording;
        
        private static SteamVR_Action_Boolean p_vRBro_togglesceneselect;
        
        private static SteamVR_Action_Boolean p_vRBro_dummy;
        
        private static SteamVR_Action_Vibration p_vRBro_Haptic;
        
        public static SteamVR_Action_Boolean vRBro_InteractUI
        {
            get
            {
                return SteamVR_Actions.p_vRBro_InteractUI.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRBro_SaveBuffer
        {
            get
            {
                return SteamVR_Actions.p_vRBro_SaveBuffer.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRBro_StartBuffer
        {
            get
            {
                return SteamVR_Actions.p_vRBro_StartBuffer.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRBro_StopBuffer
        {
            get
            {
                return SteamVR_Actions.p_vRBro_StopBuffer.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRBro_StartRecording
        {
            get
            {
                return SteamVR_Actions.p_vRBro_StartRecording.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRBro_StopRecording
        {
            get
            {
                return SteamVR_Actions.p_vRBro_StopRecording.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRBro_StartStreaming
        {
            get
            {
                return SteamVR_Actions.p_vRBro_StartStreaming.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRBro_StopStreaming
        {
            get
            {
                return SteamVR_Actions.p_vRBro_StopStreaming.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRBro_SplitRecording
        {
            get
            {
                return SteamVR_Actions.p_vRBro_SplitRecording.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRBro_togglesceneselect
        {
            get
            {
                return SteamVR_Actions.p_vRBro_togglesceneselect.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean vRBro_dummy
        {
            get
            {
                return SteamVR_Actions.p_vRBro_dummy.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration vRBro_Haptic
        {
            get
            {
                return SteamVR_Actions.p_vRBro_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.vRBro_InteractUI,
                    SteamVR_Actions.vRBro_SaveBuffer,
                    SteamVR_Actions.vRBro_StartBuffer,
                    SteamVR_Actions.vRBro_StopBuffer,
                    SteamVR_Actions.vRBro_StartRecording,
                    SteamVR_Actions.vRBro_StopRecording,
                    SteamVR_Actions.vRBro_StartStreaming,
                    SteamVR_Actions.vRBro_StopStreaming,
                    SteamVR_Actions.vRBro_SplitRecording,
                    SteamVR_Actions.vRBro_togglesceneselect,
                    SteamVR_Actions.vRBro_dummy,
                    SteamVR_Actions.vRBro_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.vRBro_InteractUI,
                    SteamVR_Actions.vRBro_SaveBuffer,
                    SteamVR_Actions.vRBro_StartBuffer,
                    SteamVR_Actions.vRBro_StopBuffer,
                    SteamVR_Actions.vRBro_StartRecording,
                    SteamVR_Actions.vRBro_StopRecording,
                    SteamVR_Actions.vRBro_StartStreaming,
                    SteamVR_Actions.vRBro_StopStreaming,
                    SteamVR_Actions.vRBro_SplitRecording,
                    SteamVR_Actions.vRBro_togglesceneselect,
                    SteamVR_Actions.vRBro_dummy};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.vRBro_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.vRBro_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[0];
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.vRBro_InteractUI,
                    SteamVR_Actions.vRBro_SaveBuffer,
                    SteamVR_Actions.vRBro_StartBuffer,
                    SteamVR_Actions.vRBro_StopBuffer,
                    SteamVR_Actions.vRBro_StartRecording,
                    SteamVR_Actions.vRBro_StopRecording,
                    SteamVR_Actions.vRBro_StartStreaming,
                    SteamVR_Actions.vRBro_StopStreaming,
                    SteamVR_Actions.vRBro_SplitRecording,
                    SteamVR_Actions.vRBro_togglesceneselect,
                    SteamVR_Actions.vRBro_dummy};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.vRBro_InteractUI,
                    SteamVR_Actions.vRBro_SaveBuffer,
                    SteamVR_Actions.vRBro_StartBuffer,
                    SteamVR_Actions.vRBro_StopBuffer,
                    SteamVR_Actions.vRBro_StartRecording,
                    SteamVR_Actions.vRBro_StopRecording,
                    SteamVR_Actions.vRBro_StartStreaming,
                    SteamVR_Actions.vRBro_StopStreaming,
                    SteamVR_Actions.vRBro_SplitRecording,
                    SteamVR_Actions.vRBro_togglesceneselect,
                    SteamVR_Actions.vRBro_dummy};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_vRBro_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRBro/in/InteractUI")));
            SteamVR_Actions.p_vRBro_SaveBuffer = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRBro/in/SaveBuffer")));
            SteamVR_Actions.p_vRBro_StartBuffer = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRBro/in/StartBuffer")));
            SteamVR_Actions.p_vRBro_StopBuffer = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRBro/in/StopBuffer")));
            SteamVR_Actions.p_vRBro_StartRecording = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRBro/in/StartRecording")));
            SteamVR_Actions.p_vRBro_StopRecording = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRBro/in/StopRecording")));
            SteamVR_Actions.p_vRBro_StartStreaming = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRBro/in/StartStreaming")));
            SteamVR_Actions.p_vRBro_StopStreaming = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRBro/in/StopStreaming")));
            SteamVR_Actions.p_vRBro_SplitRecording = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRBro/in/SplitRecording")));
            SteamVR_Actions.p_vRBro_togglesceneselect = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRBro/in/togglesceneselect")));
            SteamVR_Actions.p_vRBro_dummy = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/VRBro/in/dummy")));
            SteamVR_Actions.p_vRBro_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/VRBro/out/Haptic")));
        }
    }
}
