//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VRBro : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.vRBro_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean SaveBuffer
        {
            get
            {
                return SteamVR_Actions.vRBro_SaveBuffer;
            }
        }
        
        public virtual SteamVR_Action_Boolean StartBuffer
        {
            get
            {
                return SteamVR_Actions.vRBro_StartBuffer;
            }
        }
        
        public virtual SteamVR_Action_Boolean StopBuffer
        {
            get
            {
                return SteamVR_Actions.vRBro_StopBuffer;
            }
        }
        
        public virtual SteamVR_Action_Boolean StartRecording
        {
            get
            {
                return SteamVR_Actions.vRBro_StartRecording;
            }
        }
        
        public virtual SteamVR_Action_Boolean StopRecording
        {
            get
            {
                return SteamVR_Actions.vRBro_StopRecording;
            }
        }
        
        public virtual SteamVR_Action_Boolean StartStreaming
        {
            get
            {
                return SteamVR_Actions.vRBro_StartStreaming;
            }
        }
        
        public virtual SteamVR_Action_Boolean StopStreaming
        {
            get
            {
                return SteamVR_Actions.vRBro_StopStreaming;
            }
        }
        
        public virtual SteamVR_Action_Boolean SplitRecording
        {
            get
            {
                return SteamVR_Actions.vRBro_SplitRecording;
            }
        }
        
        public virtual SteamVR_Action_Boolean togglesceneselect
        {
            get
            {
                return SteamVR_Actions.vRBro_togglesceneselect;
            }
        }
        
        public virtual SteamVR_Action_Boolean dummy
        {
            get
            {
                return SteamVR_Actions.vRBro_dummy;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.vRBro_Haptic;
            }
        }
    }
}
